### PR TITLE
Add code coverage

### PR DESCRIPTION
**Pull request by johnynek**

### CODE REVIEW

**Comment by caniszczyk** [comment]
Similar failures here: https://travis-ci.org/twitter/chill/jobs/50141921#L1330

**Comment by johnynek** [comment]
Maybe this will work....

**Comment by johnynek** [comment]
So, somehow, this got a badge, but the log looks to me like it failed again. :/

**Comment by johnynek** [comment]
Looks like it is only picking up things from chill-scala.

**Comment by sritchie** [comment]
Covered this in #271

**Pull request closed without merging**
