### PR TITLE
Bump algebird to enable 2.12 cross build.

### PR DESCRIPTION
**Pull request by andrewsmartin**

### CODE REVIEW

**Comment by piyushnarang** [comment]
So based on comments on the algebird PR to switch to 0.12.4, I got some comments to update the version to 0.13.0. So we'll probably want to use that version once its out (waiting on some changes that @johnynek wanted to get in before I publish).

**Comment by nevillelyh** [comment]
@piyushnarang @johnynek poke again. Any plan to publish this soon?

**Comment by piyushnarang** [comment]
hey @nevillelyh, waiting on PR: https://github.com/twitter/algebird/pull/620. Once that is merged, we can publish 0.13.0. Planning to get it out in the next couple of days.

**Comment by johnynek** [comment]
so: https://github.com/twitter/algebird/pull/620 is merged, now we just need to publish `0.13.0`.

**Comment by piyushnarang** [comment]
Ok, we can pick up the 0.13.0 artifacts in chill as well. I've published 0.13.0. @andrewsmartin / @nevillelyh

**Comment by andrewsmartin** [comment]
@piyushnarang Thanks! Just updated this PR to use 0.13.0.

**Comment by johnynek** [comment]
Thank you!

**Comment by johnynek** [comment]
I think we just need to republish now and everything is on 2.10, 2.11, and 2.12

**Comment by andrewsmartin** [comment]
Thanks @johnynek! Looking forward to seeing the published artifact

**Pull request merged**
