### PR TITLE
chill-akka support scala 2.12 #266

### PR DESCRIPTION
**Pull request by fkowal**

### CODE REVIEW

**Comment by fkowal** [comment]
hmm one of travis build failed with a strange error.
sbt +test runs successfuly on my machine

can i retrigger a travis job ?

**Comment by johnynek** [comment]
That is not a strange error, that is the error when there is a mismatch between the compiled class versions and the jdk you are compiling on. In this case, I guess you need java8 for the 2.11 branch, so you need to update that in .travis.yml.

**Comment by johnynek** [comment]
@fkowal if you fix this PR to use oraclejdk8 on 2.11 tests in `.travis.yml` I'll backport this to the 0.7 and 0.8 branches so we can have things in sync there.

**Comment by fkowal** [comment]
that helped

**Comment by johnynek** [comment]
Thanks!

**Comment by mushtaq** [comment]
@johnynek I still do not see the chill-akka_2.12 artifact in mavencentral.

**Comment by johnynek** [comment]
@mushtaq should be there shortly. Was published today. cc #266

**Comment by mushtaq** [comment]
@johnynek  Thanks!

**Pull request merged**
